<?php
/**
 * Language
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Vekkon
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vekkon\PostBarcodeClient\Model;
use \Vekkon\PostBarcodeClient\ObjectSerializer;

/**
 * Language Class Doc Comment
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Vekkon
 */
class Language
{
    /**
     * Possible values of this enum
     */
    const DE = 'DE';
    const FR = 'FR';
    const IT = 'IT';
    const EN = 'EN';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DE,
            self::FR,
            self::IT,
            self::EN,
        ];
    }
}
