<?php
/**
 * NotificationType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Vekkon
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vekkon\PostBarcodeClient\Model;
use \Vekkon\PostBarcodeClient\ObjectSerializer;

/**
 * NotificationType Class Doc Comment
 *
 * @category Class
 * @description Specification of the medium.
 * @package  Vekkon\PostBarcodeClient
 * @author   Vekkon
 */
class NotificationType
{
    /**
     * Possible values of this enum
     */
    const EMAIL = 'EMAIL';
    const SMS = 'SMS';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EMAIL
            self::SMS
        ];
    }
}
