<?php
/**
 * Notification
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DIGITAL COMMERCE BARCODE API
 *
 * Digital Commerce Swiss Post web REST API for the generation of the address label. With the \"Generate address label\" request, the combinations of selected basic and additional services/delivery instructions will be tested automatically, whether or not you have already done this yourself beforehand. With the \"Generate address label\" operation, the mailing data (e.g. COD amount) is also validated. For the \"Parcels\", \"Express\" and \"Solutions\" service groups, the mailing data is automatically transferred to DataTransfer. This means that you receive the same benefits as you would under DataTransfer. API documentation https://developer.post.ch/en/digital-commerce-api
 *
 * OpenAPI spec version: 1.2
 * Contact: digitalintegration@post.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vekkon\PostBarcodeClient\Model;

use \ArrayAccess;
use \Vekkon\PostBarcodeClient\ObjectSerializer;

/**
 * Notification Class Doc Comment
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Notification implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Notification';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'communication' => '\Vekkon\PostBarcodeClient\Model\Communication',
        'service' => 'string',
        'free_text1' => 'string',
        'free_text2' => 'string',
        'delivery_instructions' => 'string[]',
        'dyn_pic' => '\Vekkon\PostBarcodeClient\Model\DynPicType',
        'language' => '\Vekkon\PostBarcodeClient\Model\Language',
        'type' => '\Vekkon\PostBarcodeClient\Model\NotificationType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'communication' => null,
        'service' => null,
        'free_text1' => null,
        'free_text2' => null,
        'delivery_instructions' => null,
        'dyn_pic' => null,
        'language' => null,
        'type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'communication' => 'communication',
        'service' => 'service',
        'free_text1' => 'freeText1',
        'free_text2' => 'freeText2',
        'delivery_instructions' => 'deliveryInstructions',
        'dyn_pic' => 'dynPic',
        'language' => 'language',
        'type' => 'type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'communication' => 'setCommunication',
        'service' => 'setService',
        'free_text1' => 'setFreeText1',
        'free_text2' => 'setFreeText2',
        'delivery_instructions' => 'setDeliveryInstructions',
        'dyn_pic' => 'setDynPic',
        'language' => 'setLanguage',
        'type' => 'setType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'communication' => 'getCommunication',
        'service' => 'getService',
        'free_text1' => 'getFreeText1',
        'free_text2' => 'getFreeText2',
        'delivery_instructions' => 'getDeliveryInstructions',
        'dyn_pic' => 'getDynPic',
        'language' => 'getLanguage',
        'type' => 'getType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const DELIVERY_INSTRUCTIONS__10 = '10';
    const DELIVERY_INSTRUCTIONS__14 = '14';
    const DELIVERY_INSTRUCTIONS__18 = '18';
    const DELIVERY_INSTRUCTIONS__20 = '20';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeliveryInstructionsAllowableValues()
    {
        return [
            self::DELIVERY_INSTRUCTIONS__10,
            self::DELIVERY_INSTRUCTIONS__14,
            self::DELIVERY_INSTRUCTIONS__18,
            self::DELIVERY_INSTRUCTIONS__20,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['communication'] = isset($data['communication']) ? $data['communication'] : null;
        $this->container['service'] = isset($data['service']) ? $data['service'] : null;
        $this->container['free_text1'] = isset($data['free_text1']) ? $data['free_text1'] : null;
        $this->container['free_text2'] = isset($data['free_text2']) ? $data['free_text2'] : null;
        $this->container['delivery_instructions'] = isset($data['delivery_instructions']) ? $data['delivery_instructions'] : null;
        $this->container['dyn_pic'] = isset($data['dyn_pic']) ? $data['dyn_pic'] : null;
        $this->container['language'] = isset($data['language']) ? $data['language'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['communication'] === null) {
            $invalidProperties[] = "'communication' can't be null";
        }
        if ($this->container['language'] === null) {
            $invalidProperties[] = "'language' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets communication
     *
     * @return \Vekkon\PostBarcodeClient\Model\Communication
     */
    public function getCommunication()
    {
        return $this->container['communication'];
    }

    /**
     * Sets communication
     *
     * @param \Vekkon\PostBarcodeClient\Model\Communication $communication communication
     *
     * @return $this
     */
    public function setCommunication($communication)
    {
        $this->container['communication'] = $communication;

        return $this;
    }

    /**
     * Gets service
     *
     * @return string
     */
    public function getService()
    {
        return $this->container['service'];
    }

    /**
     * Sets service
     *
     * @param string $service Notification code that designates the notification.
     *
     * @return $this
     */
    public function setService($service)
    {
        $this->container['service'] = $service;

        return $this;
    }

    /**
     * Gets free_text1
     *
     * @return string
     */
    public function getFreeText1()
    {
        return $this->container['free_text1'];
    }

    /**
     * Sets free_text1
     *
     * @param string $free_text1 Individual Text 1 for notification.
     *
     * @return $this
     */
    public function setFreeText1($free_text1)
    {
        $this->container['free_text1'] = $free_text1;

        return $this;
    }

    /**
     * Gets free_text2
     *
     * @return string
     */
    public function getFreeText2()
    {
        return $this->container['free_text2'];
    }

    /**
     * Sets free_text2
     *
     * @param string $free_text2 Individual Text 2 for notification..
     *
     * @return $this
     */
    public function setFreeText2($free_text2)
    {
        $this->container['free_text2'] = $free_text2;

        return $this;
    }

    /**
     * Gets delivery_instructions
     *
     * @return string[]
     */
    public function getDeliveryInstructions()
    {
        return $this->container['delivery_instructions'];
    }

    /**
     * Sets delivery_instructions
     *
     * @param string[] $delivery_instructions Possible options to indicated the delivery instructions. \"10\" Deposit consignment, \"14\" Delivery to neightbour, \"18\" Desired day, \"20\" Forward consignment
     *
     * @return $this
     */
    public function setDeliveryInstructions($delivery_instructions)
    {
        $allowedValues = $this->getDeliveryInstructionsAllowableValues();
        if (!is_null($delivery_instructions) && array_diff($delivery_instructions, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'delivery_instructions', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['delivery_instructions'] = $delivery_instructions;

        return $this;
    }

    /**
     * Gets dyn_pic
     *
     * @return \Vekkon\PostBarcodeClient\Model\DynPicType
     */
    public function getDynPic()
    {
        return $this->container['dyn_pic'];
    }

    /**
     * Sets dyn_pic
     *
     * @param \Vekkon\PostBarcodeClient\Model\DynPicType $dyn_pic dyn_pic
     *
     * @return $this
     */
    public function setDynPic($dyn_pic)
    {
        $this->container['dyn_pic'] = $dyn_pic;

        return $this;
    }

    /**
     * Gets language
     *
     * @return \Vekkon\PostBarcodeClient\Model\Language
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param \Vekkon\PostBarcodeClient\Model\Language $language language
     *
     * @return $this
     */
    public function setLanguage($language)
    {
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Vekkon\PostBarcodeClient\Model\NotificationType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Vekkon\PostBarcodeClient\Model\NotificationType $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
