<?php
/**
 * BaseRecipientTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * BaseRecipientTest Class Doc Comment
 *
 * @category    Class
 * @description BaseRecipient
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BaseRecipientTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BaseRecipient"
     */
    public function testBaseRecipient()
    {
    }

    /**
     * Test attribute "post_ident"
     */
    public function testPropertyPostIdent()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "personally_addressed"
     */
    public function testPropertyPersonallyAddressed()
    {
    }

    /**
     * Test attribute "name1"
     */
    public function testPropertyName1()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "name2"
     */
    public function testPropertyName2()
    {
    }

    /**
     * Test attribute "name3"
     */
    public function testPropertyName3()
    {
    }

    /**
     * Test attribute "address_suffix"
     */
    public function testPropertyAddressSuffix()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "house_no"
     */
    public function testPropertyHouseNo()
    {
    }

    /**
     * Test attribute "floor_no"
     */
    public function testPropertyFloorNo()
    {
    }

    /**
     * Test attribute "mailbox_no"
     */
    public function testPropertyMailboxNo()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "mobile"
     */
    public function testPropertyMobile()
    {
    }

    /**
     * Test attribute "pobox"
     */
    public function testPropertyPobox()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }
}
