<?php
/**
 * CustomerAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * CustomerAddressTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerAddress
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerAddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustomerAddress"
     */
    public function testCustomerAddress()
    {
    }

    /**
     * Test attribute "name1"
     */
    public function testPropertyName1()
    {
    }

    /**
     * Test attribute "name2"
     */
    public function testPropertyName2()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "domicile_post_office"
     */
    public function testPropertyDomicilePostOffice()
    {
    }

    /**
     * Test attribute "pobox"
     */
    public function testPropertyPobox()
    {
    }
}
