<?php
/**
 * DynPicTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * DynPicTypeTest Class Doc Comment
 *
 * @category    Class
 * @description is only a valid input for Post-internal applications. For Post-external applications the DynPic must not be set.
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DynPicTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DynPicType"
     */
    public function testDynPicType()
    {
    }

    /**
     * Test attribute "url_pic"
     */
    public function testPropertyUrlPic()
    {
    }

    /**
     * Test attribute "url_link"
     */
    public function testPropertyUrlLink()
    {
    }
}
