<?php
/**
 * GenerateLabelDefinitionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * GenerateLabelDefinitionTest Class Doc Comment
 *
 * @category    Class
 * @description GenerateLabelDefinition
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GenerateLabelDefinitionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GenerateLabelDefinition"
     */
    public function testGenerateLabelDefinition()
    {
    }

    /**
     * Test attribute "label_layout"
     */
    public function testPropertyLabelLayout()
    {
    }

    /**
     * Test attribute "print_addresses"
     */
    public function testPropertyPrintAddresses()
    {
    }

    /**
     * Test attribute "image_file_type"
     */
    public function testPropertyImageFileType()
    {
    }

    /**
     * Test attribute "image_resolution"
     */
    public function testPropertyImageResolution()
    {
    }

    /**
     * Test attribute "print_preview"
     */
    public function testPropertyPrintPreview()
    {
    }
}
