<?php
/**
 * GenerateLabelResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * GenerateLabelResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GenerateLabelResponse
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GenerateLabelResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GenerateLabelResponse"
     */
    public function testGenerateLabelResponse()
    {
    }

    /**
     * Test attribute "label_definition"
     */
    public function testPropertyLabelDefinition()
    {
    }

    /**
     * Test attribute "sending_id"
     */
    public function testPropertySendingId()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }
}
