<?php
/**
 * GenerateLabelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * GenerateLabelTest Class Doc Comment
 *
 * @category    Class
 * @description GenerateLabel
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GenerateLabelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GenerateLabel"
     */
    public function testGenerateLabel()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "franking_license"
     */
    public function testPropertyFrankingLicense()
    {
    }

    /**
     * Test attribute "pp_franking"
     */
    public function testPropertyPpFranking()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "customer_system"
     */
    public function testPropertyCustomerSystem()
    {
    }

    /**
     * Test attribute "label_definition"
     */
    public function testPropertyLabelDefinition()
    {
    }

    /**
     * Test attribute "sending_id"
     */
    public function testPropertySendingId()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }
}
