<?php
/**
 * GenerateLabelCustomerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DIGITAL COMMERCE BARCODE API
 *
 * Digital Commerce Swiss Post web REST API for the generation of the address label. With the \"Generate address label\" request, the combinations of selected basic and additional services/delivery instructions will be tested automatically, whether or not you have already done this yourself beforehand. With the \"Generate address label\" operation, the mailing data (e.g. COD amount) is also validated. For the \"Parcels\", \"Express\" and \"Solutions\" service groups, the mailing data is automatically transferred to DataTransfer. This means that you receive the same benefits as you would under DataTransfer. API documentation https://developer.post.ch/en/digital-commerce-api
 *
 * OpenAPI spec version: 1.2
 * Contact: digitalintegration@post.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * GenerateLabelCustomerTest Class Doc Comment
 *
 * @category    Class
 * @description GenerateLabelCustomer
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GenerateLabelCustomerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GenerateLabelCustomer"
     */
    public function testGenerateLabelCustomer()
    {
    }

    /**
     * Test attribute "name1"
     */
    public function testPropertyName1()
    {
    }

    /**
     * Test attribute "name2"
     */
    public function testPropertyName2()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "logo_format"
     */
    public function testPropertyLogoFormat()
    {
    }

    /**
     * Test attribute "logo_rotation"
     */
    public function testPropertyLogoRotation()
    {
    }

    /**
     * Test attribute "logo_aspect_ratio"
     */
    public function testPropertyLogoAspectRatio()
    {
    }

    /**
     * Test attribute "logo_horizontal_align"
     */
    public function testPropertyLogoHorizontalAlign()
    {
    }

    /**
     * Test attribute "logo_vertical_align"
     */
    public function testPropertyLogoVerticalAlign()
    {
    }

    /**
     * Test attribute "domicile_post_office"
     */
    public function testPropertyDomicilePostOffice()
    {
    }

    /**
     * Test attribute "pobox"
     */
    public function testPropertyPobox()
    {
    }
}
