<?php
/**
 * GenerateSingleBarcodesResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * GenerateSingleBarcodesResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GenerateSingleBarcodesResponse
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GenerateSingleBarcodesResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GenerateSingleBarcodesResponse"
     */
    public function testGenerateSingleBarcodesResponse()
    {
    }

    /**
     * Test attribute "barcode_definition"
     */
    public function testPropertyBarcodeDefinition()
    {
    }

    /**
     * Test attribute "sending_id"
     */
    public function testPropertySendingId()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }
}
