<?php
/**
 * LabelAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * LabelAddressTest Class Doc Comment
 *
 * @category    Class
 * @description Optional, used to declare a specific address on the label.  If omitted, the address data of the recipient is taken.  Useful if the address data of the recipient exceeds the length of the label.
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LabelAddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LabelAddress"
     */
    public function testLabelAddress()
    {
    }

    /**
     * Test attribute "label_line"
     */
    public function testPropertyLabelLine()
    {
    }
}
