<?php
/**
 * ReplacementRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * ReplacementRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ReplacementRequest
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReplacementRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReplacementRequest"
     */
    public function testReplacementRequest()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "customer_details"
     */
    public function testPropertyCustomerDetails()
    {
    }

    /**
     * Test attribute "send_replacement"
     */
    public function testPropertySendReplacement()
    {
    }

    /**
     * Test attribute "return_to_warehouse"
     */
    public function testPropertyReturnToWarehouse()
    {
    }

    /**
     * Test attribute "send_repaired"
     */
    public function testPropertySendRepaired()
    {
    }

    /**
     * Test attribute "return_replacement"
     */
    public function testPropertyReturnReplacement()
    {
    }
}
