<?php
/**
 * ReplacementCustomerDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * ReplacementCustomerDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description ReplacementCustomerDetails
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReplacementCustomerDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReplacementCustomerDetails"
     */
    public function testReplacementCustomerDetails()
    {
    }

    /**
     * Test attribute "license_no"
     */
    public function testPropertyLicenseNo()
    {
    }

    /**
     * Test attribute "label_layout"
     */
    public function testPropertyLabelLayout()
    {
    }

    /**
     * Test attribute "image_file_type"
     */
    public function testPropertyImageFileType()
    {
    }

    /**
     * Test attribute "image_resolution"
     */
    public function testPropertyImageResolution()
    {
    }

    /**
     * Test attribute "print_preview"
     */
    public function testPropertyPrintPreview()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }
}
