<?php
/**
 * ReplacementLabelResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * ReplacementLabelResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ReplacementLabelResponse
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReplacementLabelResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReplacementLabelResponse"
     */
    public function testReplacementLabelResponse()
    {
    }

    /**
     * Test attribute "identcode"
     */
    public function testPropertyIdentcode()
    {
    }

    /**
     * Test attribute "image_file_type"
     */
    public function testPropertyImageFileType()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }
}
