<?php
/**
 * ReturnInfoTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * ReturnInfoTypeTest Class Doc Comment
 *
 * @category    Class
 * @description ReturnInfoType
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReturnInfoTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReturnInfoType"
     */
    public function testReturnInfoType()
    {
    }

    /**
     * Test attribute "return_note"
     */
    public function testPropertyReturnNote()
    {
    }

    /**
     * Test attribute "instruction_for_returns"
     */
    public function testPropertyInstructionForReturns()
    {
    }

    /**
     * Test attribute "return_service"
     */
    public function testPropertyReturnService()
    {
    }

    /**
     * Test attribute "customer_id_return_address"
     */
    public function testPropertyCustomerIdReturnAddress()
    {
    }
}
