<?php
/**
 * ServiceCodeAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vekkon\PostBarcodeClient;

use PHPUnit\Framework\TestCase;

/**
 * ServiceCodeAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description ServiceCodeAttributes
 * @package     Vekkon\PostBarcodeClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceCodeAttributesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServiceCodeAttributes"
     */
    public function testServiceCodeAttributes()
    {
    }

    /**
     * Test attribute "przl"
     */
    public function testPropertyPrzl()
    {
    }

    /**
     * Test attribute "free_text"
     */
    public function testPropertyFreeText()
    {
    }

    /**
     * Test attribute "delivery_date"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "parcel_no"
     */
    public function testPropertyParcelNo()
    {
    }

    /**
     * Test attribute "parcel_total"
     */
    public function testPropertyParcelTotal()
    {
    }

    /**
     * Test attribute "delivery_place"
     */
    public function testPropertyDeliveryPlace()
    {
    }

    /**
     * Test attribute "pro_clima"
     */
    public function testPropertyProClima()
    {
    }

    /**
     * Test attribute "return_info"
     */
    public function testPropertyReturnInfo()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "unnumbers"
     */
    public function testPropertyUnnumbers()
    {
    }

    /**
     * Test attribute "dispatch_info"
     */
    public function testPropertyDispatchInfo()
    {
    }
}
