<?php
/**
 * SingleBarcodeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */


/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Vekkon\PostBarcodeClient;

use Vekkon\PostBarcodeClient\Configuration;
use Vekkon\PostBarcodeClient\ApiException;
use Vekkon\PostBarcodeClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SingleBarcodeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Vekkon\PostBarcodeClient
 * @author   Swagger Codegen team

 */
class SingleBarcodeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for generateSingleBarcodes
     *
     * Generate Single Barcode.
     *
     */
    public function testGenerateSingleBarcodes()
    {
    }
}
